title: Franziska Vollmer
#logo: \20230905_144121.jpg
show_downloads: false
#description: E-Mail: franziska-vollmer@outlook.com, LinkedIn: https://www.linkedin.com/in/franziska-vollmer-643195201/
theme: jekyll-theme-minimal
